GET http://localhost:3000/players/
###

POST http://localhost:3000/players/
Content-Type: "application/json"

{
  "playerName": "Omesh",
  "jerseyNumber": 9,
  "role": "All-rounder"
}
###

GET http://localhost:3000/players/9/
###

PUT http://localhost:3000/players/7/
Content-Type: "application/json"

{
  "playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rounder"
}
###


DELETE http://localhost:3000/players/6/
